# Generated by Django 5.2.17 on 2026-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatusevent",
            name="from_status",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="to_status",
            field=models.CharField(max_length=40),
        ),
    ]
