# Generated by Django 5.2.17 on 2026-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderstatusevent_from_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
