# Generated by Django 5.2.17 on 2026-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
