# Generated by Django 5.2.17 on 2026-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_image_url_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Unlisted products stay for order history but drop out of the public catalog.",
            ),
        ),
    ]
