# Generated by Django 5.2.17 on 2026-09-14 15:17

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image_url"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="product",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="product_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
